# Acquisition
ACQUISITION_COST = 1_237_000
PROPERTY_SQFT = 4797
HOLD_TERM_YEARS = 10

# Income
GROSS_POTENTIAL_RENT = 78750
YEAR_OVER_YEAR_RENT_INCREASE = 0.02

# Disclaimers
VACANCY_PERCENTAGE = 0.06
ASSET_MANAGEMENT_FEE_PERCENTAGE = 0.01

# annual expenses
ANNUAL_TAX_COST = 0
ANNUAL_INSURANCE = 0
RM_TURN_AND_CONT_SVCS = 0
ADMIN_AND_MARKETING = 0
UTILITIES = 0
REPLACEMENT_RESERVES = 0
PERSONNEL = 0
PROPERTY_MANAGEMENT_FEE = 0.05

# Hard costs
GENERAL_CONDITIONS_AND_OTHER = 0
GC_OVERHEAD_PERCENTAGE = 0.08
SITE_COSTS = 0
BUILDING_CONSTRUCTION = 0
MEPS = 0
CONTIGENCY_PERCENTAGE = 0.08

# Soft costs
## Due diligence
TRANSFER_AND_RECORDATION_TAX = 0
LEGAL_FEES = 0
DUE_DILIGENCE = 0
TITLE_INSURANCE = 0

CONSTRUCTION_MANAGEMENT_PERCENTAGE = 0.03
MARKET_STUDY = 0
ARCHITECTURAL = 0
GEOTECH = 0
CIVIL_END_LANDSCAPE_DESIGN = 0
STRUCTURAL = 0
MEP = 0
MARKETING_PROMOTIONAL = 0
BROKERAGE_FEES = 0
IMPACT_FEES = 0
LEGAL_CONSTRUCTION = 0
LEGAL_LEASING = 0
LEGAL_DEVELOPMENT = 0
BUILDERS_RISK_INSURANCE = 0
PROPERTY_TAXES_DURING_CONSTRUCTION = 0
# As percentage of soft costs
CONTINGENCY_PERCENTAGE_SOFT_COSTS = 0.05

# Financing Assumptions
LTV_PERCENTAGE = 0.76
INTEREST = 0.04
AMORTIZATION_YEARS = 30
## Financing Costs
APPRAISAL = 0
LEGAL_LOAN = 0
LEGAL_PPM = 0
POINTS_AND_FEES = 22000
CONTIGENCY_PERCENTAGE_FINANCING = 0
DEVELOPMENT_FEE_PERCENTAGE = 0.02
WORKING_CAPITAL = 750


# Prelim Due Diligence and Design Costs
PHASE_1_ENV = 2000
PCA = 2500
ALTA_SURVEY = 6500
TRAVEL = 500
PLATTING = 2500
PRELIM_SITE_PLAN = 0
PRELIM_STORMW_STUDY = 25000
TRAFFIC_STUDIES = 5000
EASEMENTS = 600
